Update file edit-config, affecting net-analyzer/netdata
Signed-off-by: Stuart Shelton <stuart@shelton.me>

diff --git a/net-analyzer/netdata/files/edit-config b/net-analyzer/netdata/files/edit-config
--- a/net-analyzer/netdata/files/edit-config
+++ b/net-analyzer/netdata/files/edit-config
@@ -43,11 +43,17 @@ abspath() {
 	if [ -d "${1}/" ]; then
 		echo "$(cd "${1}" && /usr/bin/env PWD= pwd -P)/"
 	elif [ -f "${1}" ]; then
-		echo "$(cd "$(dirname "${1}")" && /usr/bin/env PWD= pwd -P)/$(basename "${1}")"
+		echo "$(
+			cd "$(dirname "${1}")" &&
+				/usr/bin/env PWD= pwd -P
+		)/$(basename "${1}")"
 	elif echo "${1}" | grep -q '/'; then
 		if echo "${1}" | grep -q '^/'; then
 			mkdir -p "$(dirname "${1}")"
-			echo "$(cd "$(dirname "${1}")" && /usr/bin/env PWD= pwd -P)/$(basename "${1}")"
+			echo "$(
+				cd "$(dirname "${1}")" &&
+					/usr/bin/env PWD= pwd -P
+			)/$(basename "${1}")"
 		else
 			mkdir -p "${script_dir}/$(dirname "${1}")"
 			echo "${script_dir}/${1}"
@@ -76,9 +82,13 @@ check_directories() {
 		PATH="${OLDPATH}"
 	fi
 
-	if [ -n "${NETDATA_PREFIX}" ] && [ -d "${NETDATA_PREFIX}/usr/lib/netdata/conf.d" ]; then
+	if [ -n "${NETDATA_PREFIX}" ] &&
+			[ -d "${NETDATA_PREFIX}/usr/lib/netdata/conf.d" ]
+	then
 		stock_dir="${NETDATA_PREFIX}/usr/lib/netdata/conf.d"
-	elif [ -n "${NETDATA_PREFIX}" ] && [ -d "${NETDATA_PREFIX}/lib/netdata/conf.d" ]; then
+	elif [ -n "${NETDATA_PREFIX}" ] &&
+			[ -d "${NETDATA_PREFIX}/lib/netdata/conf.d" ]
+	then
 		stock_dir="${NETDATA_PREFIX}/lib/netdata/conf.d"
 	elif [ -d "${script_dir}/../../usr/lib/netdata/conf.d" ]; then
 		stock_dir="${script_dir}/../../usr/lib/netdata/conf.d"
@@ -88,8 +98,10 @@ check_directories() {
 		stock_dir="/usr/lib/netdata/conf.d"
 	fi
 
-	[ -z "${NETDATA_USER_CONFIG_DIR}" ] && NETDATA_USER_CONFIG_DIR="${script_dir}"
-	[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] && NETDATA_STOCK_CONFIG_DIR="${stock_dir}"
+	[ -z "${NETDATA_USER_CONFIG_DIR}" ] &&
+		NETDATA_USER_CONFIG_DIR="${script_dir}"
+	[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] &&
+		NETDATA_STOCK_CONFIG_DIR="${stock_dir}"
 
 	if [ -z "${NETDATA_STOCK_CONFIG_DIR}" ]; then
 		error "Unable to find stock config directory."
@@ -99,18 +111,24 @@ check_directories() {
 
 check_editor() {
 	if [ -z "${editor}" ]; then
-		if [ -n "${EDITOR}" ] && command -v "${EDITOR}" >/dev/null 2>&1; then
+		if [ -n "${EDITOR:-}" ] &&
+				command -v "${EDITOR}" >/dev/null 2>&1
+		then
 			editor="${EDITOR}"
 		elif command -v editor >/dev/null 2>&1; then
 			editor="editor"
+		elif command -v vim >/dev/null 2>&1; then
+			editor="vim"
 		elif command -v vi >/dev/null 2>&1; then
 			editor="vi"
 		else
-			error "Unable to find a usable editor, tried \${EDITOR} (${EDITOR}), editor, and vi."
+			error "Unable to find a usable editor, tried" \
+				"\${EDITOR} (${EDITOR}), editor, vim and vi."
 			exit 1
 		fi
 	elif ! command -v "${editor}" >/dev/null 2>&1; then
-		error "Unable to locate user specified editor ${editor}, is it in your PATH?"
+		error "Unable to locate user specified editor ${editor}, is" \
+			"it in your PATH?"
 		exit 1
 	fi
 }
@@ -119,13 +137,17 @@ running_in_container() {
 	[ -e /.dockerenv ] && return 0
 	[ -e /.dockerinit ] && return 0
 	[ -e /run/.containerenv ] && return 0
-	[ -r /proc/1/environ ] && tr '\000' '\n' </proc/1/environ | grep -Eiq 'container=' && return 0
-	grep -qF -e /docker/ -e /libpod- /proc/self/cgroup 2>/dev/null && return 0
+	[ -r /proc/1/environ ] &&
+				tr '\000' '\n' </proc/1/environ |
+			grep -Eiq 'container=' &&
+		return 0
+	grep -qF -e /docker/ -e /libpod- /proc/self/cgroup 2>/dev/null &&
+		return 0
 	return 1
 }
 
 get_docker_command() {
-	if [ -x "${docker}" ]; then
+	if [ -n "${docker:-}" ] && [ -x "${docker% *}" ]; then
 		return 0
 	elif command -v podman >/dev/null 2>&1; then
 		docker="$(command -v podman)"
@@ -133,48 +155,65 @@ get_docker_command() {
 			mkdir -p /etc/containers 2>/dev/null &&
 				touch /etc/containers/nodocker 2>/dev/null
 		fi
+		if [ -S /var/run/docker.sock ]; then
+			export DOCKER_HOST="unix:///var/run/docker.sock"
+			${docker} system connection add --default host \
+				"unix:///var/run/docker.sock"
+			docker="${docker} -c"
+		fi
 	elif command -v docker >/dev/null 2>&1; then
 		docker="$(command -v docker)"
 	else
-		error "Unable to find a usable container tool stack. I support Docker and Podman."
+		error "Unable to find a usable container tool stack." \
+			"I support Docker and Podman."
 		exit 1
 	fi
 }
 
 run_in_container() {
 	get_docker_command
-	#echo >&2 "DEBUG: Running command '${2}' in container '${1}' with command '${docker}'"
+	#echo >&2 "DEBUG: Running command '${2}' in container '${1}' with" \
+	#	"command '${docker}'"
 	${docker} exec "${1}" /bin/sh -c "${2}" || return 1
 	return 0
 }
 
 check_for_container() {
 	get_docker_command
-	#echo >&2 "DEBUG: Running 'inspect' on container '${1}' with command '${docker}'"
+	#echo >&2 "DEBUG: Running 'inspect' on container '${1}' with command" \
+	#	"'${docker}'"
 	${docker} container inspect "${1}" >/dev/null 2>&1 || return 1
-	run_in_container "${1}" "[ -d \"${NETDATA_STOCK_CONFIG_DIR}\" ]" >/dev/null 2>&1 || return 1
+	run_in_container "${1}" "[ -d \"${NETDATA_STOCK_CONFIG_DIR}\" ]" \
+		>/dev/null 2>&1 || return 1
 	return 0
 }
 
 handle_container() {
 	if running_in_container; then
 		return 0
-	elif [ -z "${container}" ] && [ -f "${script_dir}/.container-hostname" ]; then
-		echo >&2 "Autodetected containerized Netdata instance. Attempting to autodetect container ID."
+
+	elif [ -z "${container_name:-}" ] &&
+			[ -f "${script_dir}/.container-hostname" ]
+	then
+		echo >&2 "Autodetected containerized Netdata instance"
 		possible_container="$(cat "${script_dir}/.container-hostname")"
+		echo >&2 "Attempting to autodetect container ID" \
+			"'${possible_container}'"
 		if check_for_container "${possible_container}"; then
-			container="${possible_container}"
+			container_name="${possible_container}"
 		elif check_for_container netdata; then
-			container="netdata"
+			container_name="netdata"
 		else
-			error "Could not autodetect container ID. It must be supplied on the command line with the --container option."
+			error "Could not autodetect container ID. It must be" \
+				"supplied on the command line with the" \
+				"--container option."
 			exit 1
 		fi
 
-		echo >&2 "Found Netdata container with ID or name ${container}"
-	elif [ -n "${container}" ]; then
-		if ! check_for_container "${container}"; then
-			error "No container with ID or name ${container} exists."
+		echo >&2 "Found Netdata container with ID or name ${container_name}"
+	elif [ -n "${container_name}" ]; then
+		if ! check_for_container "${container_name}"; then
+			error "No container with ID or name ${container_name} exists."
 			exit 1
 		fi
 	fi
@@ -188,34 +227,51 @@ list_files() {
 		width="$(tput cols)"
 	fi
 
-	if [ -z "${container}" ]; then
+	if [ -z "${container_name:-}" ]; then
 		if [ "$(uname -s)" = "Linux" ]; then
 			# shellcheck disable=SC2046,SC2086
-			files="$(cd "${NETDATA_STOCK_CONFIG_DIR}" && ls ${width:+-C} ${width:+-w ${width}} $(find . -type f | cut -d '/' -f 2-))"
+			files="$(
+				cd "${NETDATA_STOCK_CONFIG_DIR}" &&
+				ls ${width:+-C} ${width:+-w ${width}} $(
+					find . -type f | cut -d '/' -f 2-
+				)
+			)"
 		elif [ "$(uname -s)" = "FreeBSD" ]; then
 			if [ -n "${width}" ]; then
 				export COLUMNS="${width}"
 			fi
 
 			# shellcheck disable=SC2046
-			files="$(cd "${NETDATA_STOCK_CONFIG_DIR}" && ls ${width:+-C} $(find . -type f | cut -d '/' -f 2-))"
+			files="$(
+				cd "${NETDATA_STOCK_CONFIG_DIR}" &&
+				ls ${width:+-C} $(
+					find . -type f | cut -d '/' -f 2-
+				)
+			)"
 		else
 			# shellcheck disable=SC2046
-			files="$(cd "${NETDATA_STOCK_CONFIG_DIR}" && ls $(find . -type f | cut -d '/' -f 2-))"
+			files="$(
+				cd "${NETDATA_STOCK_CONFIG_DIR}" &&
+				ls $(
+					find . -type f | cut -d '/' -f 2-
+				)
+			)"
 		fi
 	else
-		files="$(run_in_container "${container}" "cd /usr/lib/netdata/conf.d && ls ${width:+-C} ${width:+-w ${width}} \$(find . -type f | cut -d '/' -f 2-)")"
+		files="$(run_in_container "${container_name}" \
+			"cd /usr/lib/netdata/conf.d && ls ${width:+-C} ${width:+-w ${width}} \$(find . -type f | cut -d '/' -f 2-)"
+		)"
 	fi
 
-	if [ -z "${files}" ]; then
+	if [ -z "${files:-}" ]; then
 		error "Failed to find any configuration files."
 		exit 1
 	fi
 
-	cat <<EOF
-The following configuration files are known to this script:
+	cat <<-EOF
+	The following configuration files are known to this script:
 
-${files}
+	${files}
 EOF
 	exit 0
 }
@@ -235,28 +291,31 @@ parse_args() {
 				fi
 				;;
 			"--container")
-				if [ -n "${2}" ]; then
-					container="${2}"
+				if [ -n "${2:-}" ]; then
+					container_name="${2}"
 					shift 1
 				else
-					error "No container ID or name specified with the --container option."
+					error "No container ID or name" \
+						"specified with the" \
+						"--container option."
 					exit 1
 				fi
 				;;
 			"--no-container")
-				unset container
+				unset container_name
 				;;
 			"--editor")
 				if [ -n "${2}" ]; then
 					editor="${2}"
 					shift 1
 				else
-					error "No editor specified with the --editor option."
+					error "No editor specified with the" \
+						"--editor option."
 					exit 1
 				fi
 				;;
 			*)
-				if [ -z "${2}" ]; then
+				if [ -z "${2:-}" ]; then
 					file="${1}"
 				else
 					error "Unrecognized option ${1}."
@@ -285,10 +344,12 @@ copy_native() {
 	fi
 
 	if [ -f "${NETDATA_STOCK_CONFIG_DIR}/${1}" ]; then
-		echo >&2 "Copying '${NETDATA_STOCK_CONFIG_DIR}/${1}' to '${NETDATA_USER_CONFIG_DIR}/${1}' ... "
-		cp -p "${NETDATA_STOCK_CONFIG_DIR}/${1}" "${NETDATA_USER_CONFIG_DIR}/${1}" || exit 1
+		echo >&2 "Copying '${NETDATA_STOCK_CONFIG_DIR}/${1}' to" \
+			"'${NETDATA_USER_CONFIG_DIR}/${1}' ... "
+		cp -p "${NETDATA_STOCK_CONFIG_DIR}/${1}" \
+			"${NETDATA_USER_CONFIG_DIR}/${1}" || exit 1
 	else
-		echo >&2 "Creating empty '${NETDATA_USER_CONFIG_DIR}/${1}' ... "
+		echo >&2 "Creating empty '${NETDATA_USER_CONFIG_DIR}/${1}' ..."
 		touch "${NETDATA_USER_CONFIG_DIR}/${1}" || exit 1
 	fi
 }
@@ -300,11 +361,15 @@ copy_container() {
 	fi
 
 	get_docker_command
-	if run_in_container "${container}" "[ -f \"${NETDATA_STOCK_CONFIG_DIR}/${1}\" ]"; then
-		echo >&2 "Copying '${NETDATA_STOCK_CONFIG_DIR}/${1}' to '${NETDATA_USER_CONFIG_DIR}/${1}' ... "
-		${docker} cp -a "${container}:${NETDATA_STOCK_CONFIG_DIR}/${1}" "${NETDATA_USER_CONFIG_DIR}/${1}" || exit 1
+	if run_in_container "${container_name}" \
+			"[ -f \"${NETDATA_STOCK_CONFIG_DIR}/${1}\" ]"
+	then
+		echo >&2 "Copying '${NETDATA_STOCK_CONFIG_DIR}/${1}' to" \
+			"'${NETDATA_USER_CONFIG_DIR}/${1}' ..."
+		${docker} cp -a "${container_name}:${NETDATA_STOCK_CONFIG_DIR}/${1}" \
+			"${NETDATA_USER_CONFIG_DIR}/${1}" || exit 1
 	else
-		echo >&2 "Creating empty '${NETDATA_USER_CONFIG_DIR}/${1}' ... "
+		echo >&2 "Creating empty '${NETDATA_USER_CONFIG_DIR}/${1}' ..."
 		touch "${NETDATA_USER_CONFIG_DIR}/${1}" || exit 1
 	fi
 }
@@ -312,7 +377,7 @@ copy_container() {
 copy() {
 	if [ -f "${NETDATA_USER_CONFIG_DIR}/${1}" ]; then
 		return 0
-	elif [ -n "${container}" ]; then
+	elif [ -n "${container_name}" ]; then
 		copy_container "${1}"
 	else
 		copy_native "${1}"
