Update init scripts to remove bash-specific syntax

diff --git a/www-apps/rpi-monitor/files/rpimonitor.initd b/www-apps/rpi-monitor/files/rpimonitor.initd
--- a/www-apps/rpi-monitor/files/rpimonitor.initd
+++ b/www-apps/rpi-monitor/files/rpimonitor.initd
@@ -3,37 +3,44 @@
 # Distributed under the terms of the GNU General Public License v2
 
 PERL="$( type -pf perl )"
-NAME=rpimonitord
-PIDFILE=/var/run/$NAME.pid
-DAEMON=/usr/sbin/$NAME
-DAEMON_ARGS="-b ${PIDFILE} ${CONFFILES:+${CONFFILES}}"
+NAME="rpimonitord"
+PIDFILE="/var/run/${NAME}.pid"
+DAEMON="/usr/sbin/${NAME}"
+DAEMON_ARGS="-b ${PIDFILE}${CONFFILES:+ ${CONFFILES}}"
 
 depend() {
 	need net
 }
 
 start() {
-	[[ -x "$PERL" ]] || { eerror "Cannot locate perl binary" ; return 1 ; }
+	if ! [ -x "${PERL}" ]; then
+		eerror "Cannot locate perl binary"
+		return 1
+	fi
 
 	ebegin "Starting RPi Monitor"
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $PERL -- $DAEMON $DAEMON_ARGS
-	eend $? "Unable to start RPi Monitor"
+	start-stop-daemon --start --quiet --pidfile "${PIDFILE}" --exec "${PERL}" -- "${DAEMON}" ${DAEMON_ARGS}
+	eend ${?} "Unable to start RPi Monitor"
 }
 
 stop() {
-	local pid pids rc
-	[[ -r "$PIDFILE" ]] && pids="$( cat "$PIDFILE" )"
+	local pid pids
+	declare -i pid
 
 	ebegin "Stopping RPi Monitor"
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $PERL
-	rc=$?
-	[[ -n "$pids" ]] && for pid in $pids; do
-		ps -o args= $pid | grep -q "${PIDFILE}$" && {
-			eindent
-			einfo "Sending HUP signal to child $pid ..."
-			kill -HUP $pid
-			eoutdent
-		}
-	done
-	eend $rc "Unable to stop RPi Monitor"
+	if [ -r "${PIDFILE}" ]; then
+		pids="$( cat "${PIDFILE}" )"
+		if [ -n "${pids}" ]; then
+			for pid in ${pids}; do
+				if ps -o args= ${pid} | grep -q "${PIDFILE}$"; then
+					eindent
+					einfo "Sending HUP signal to child ${pid} ..."
+					kill -HUP ${pid}
+					eoutdent
+				fi
+			done
+		fi
+	fi
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile "${PIDFILE}" --exec "${PERL}"
+	eend ${?} "Unable to stop RPi Monitor"
 }
