Update sys-apps/busybox with mdev fixes for Bluetooth HCI devices

diff --git a/sys-apps/busybox/files/mdev/usb b/sys-apps/busybox/files/mdev/usb
--- a/sys-apps/busybox/files/mdev/usb
+++ b/sys-apps/busybox/files/mdev/usb
@@ -28,16 +28,26 @@ log "usb helper started as '$0' in '$( pwd )', MDEV '$MDEV', ACTION '$ACTION', D
 
 [ -n "$MDEV" ] || exit 0
 [ -n "$DEVPATH" ] || exit 0
-[ "$SUBSYSTEM" = "usb" ] || exit 0
+#[ "$SUBSYSTEM" = "usb" ] || exit 0
 
 # e.g. DEVPATH=/devices/pci0000:00/0000:00:0f.4/usb2/2-1, MDEV=2-1
 #  or  DEVPATH=/devices/platform/bcm2708_usb/usb1/1-1/1-1.1, MDEV=1-1.1
+#  or  DEVPATH=/devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.4/1-1.3.4.1/1-1.3.4.1:1.0/bluetooth/hci0/hci0:40, MDEV=hci0:40 (which doesn't exist)
 BUS=""
 USB_DEV=""
 USB_VENDOR=""
 USB_PRODUCT=""
 PRODUCT=""
 IPHETH="/lib/udev/ipheth-pair"
+
+if ! [ -s "/sys$DEVPATH/busnum" ]; then
+	DEVPATH="$( echo "$DEVPATH" | grep -o '^.*/[0-9]\+-[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/' )"
+	DEVPATH="${DEVPATH%/}"
+fi
+if ! [ -s "/sys$DEVPATH/busnum" ]; then
+	log "Could not determine valid DEVPATH for node '$MDEV' from string '$DEVPATH' - aborting"
+	exit 1
+fi
 
 if [ -d /sys/devices ]; then
 	BUS="$( add_zeros "$( cat "/sys$DEVPATH/busnum" 2>/dev/null )" )"
@@ -77,12 +87,41 @@ case "$ACTION" in
 		if [ ! -d "bus/usb/$BUS" ]; then
 			log "WARNING USB bus directory 'bus/usb/$BUS' doesn't exist - is USB initialised?"
 			mkdir -p "bus/usb/$BUS" \
-				&& log "mkdir succeeded for 'bus/usb/$BUS'" \
-				|| { log "mkdir failed for 'bus/usb/$BUS'" ; exit 0 ; }
+				&&   log "mkdir succeeded for 'bus/usb/$BUS'" \
+				|| { log "mkdir failed for 'bus/usb/$BUS': $?" ; exit 0 ; }
+		fi
+		if [ ! -e "$MDEV" ]; then
+			# Device-node doesn't exist - attempt to recover vitals
+			# from $DEVPATH/dev ...
+			if [ -s "/sys$DEVPATH/dev" ]; then
+				major="$( cat "/sys$DEVPATH/dev" | cut -d':' -f 1 )"
+				minor="$( cat "/sys$DEVPATH/dev" | cut -d':' -f 2 )"
+				if [ -n "$major" -a -n "$minor" ]; then
+					mknod "$MDEV" 'c' "$major" "$minor" \
+						&&   log "mknod succeeded for '$MDEV'" \
+						|| { log "mknod failed for '$MDEV' ($major:$minor): $?" ; exit 1 ; }
+				fi
+			fi
 		fi
 		mv "$MDEV" "bus/usb/$BUS/$USB_DEV" \
-			&& log "mv succeeded for 'bus/usb/$BUS/$USB_DEV'" \
-			|| { log "mv failed for 'bus/usb/$BUS/$USB_DEV'" ; exit 0 ; }
+			&&   log "mv succeeded for 'bus/usb/$BUS/$USB_DEV'" \
+			|| { log "mv failed for 'bus/usb/$BUS/$USB_DEV': $?" ; exit 0 ; }
+
+		# Handle specific subsystems
+		case "$SUBSYSTEM" in
+			bluetooth)
+				if [ ! -d "hci" ]; then
+					log "WARNING HCI directory 'hci' doesn't exist"
+					mkdir -p "hci" \
+						&& log "mkdir succeeded for 'hci'" \
+						|| log "mkdir failed for 'hci': $?"
+				fi
+				if [ -d "hci" ]; then
+					ln -s "../bus/usb/$BUS/$USB_DEV" "hci/$MDEV"
+					ln -s "hci/$MDEV" "$MDEV"
+				fi
+				;;
+		esac
 
 		# Setup iPhone, if present
 		if [ -x "/usr/sbin/usbmuxd" -a -x "$IPHETH" ]; then
@@ -124,16 +163,38 @@ case "$ACTION" in
 			fi
 		fi
 
+		# Handle specific subsystems
+		case "$SUBSYSTEM" in
+			bluetooth)
+				if [ -d "hci" -a -e "hci/$MDEV" ]; then
+					if rm -f "hci/$MDEV" 2>/dev/null \
+						&& log "rm -f 'hci/$MDEV' succeeded"
+					then
+						rmdir -p "hci" 2>/dev/null \
+							&& log "rmdir -p 'hci' succeeded" \
+							|| log "rmdir -p 'hci' failed: $?"
+					else
+						log "rm -f 'hci/$MDEV' failed: $?"
+					fi
+					if rm -f "$MDEV" 2>/dev/null; then
+						log "rm -f '$MDEV' succeeded"
+					else
+						log "rm -f '$MDEV' failed: $?"
+					fi
+				fi
+				;;
+		esac
+
 		# Remove device node and potential empty directories
 		if rm -f "bus/usb/$BUS/$USB_DEV" 2>/dev/null \
 			&& log "rm -f 'bus/usb/$BUS/$USB_DEV' succeeded"
 		then
 			rmdir -p "bus/usb/$BUS" 2>/dev/null \
 				&& log "rmdir -p 'bus/usb/$BUS' succeeded" \
-				|| { log "rmdir -p 'bus/usb/$BUS' failed" ; exit 0 ; }
+				|| log "rmdir -p 'bus/usb/$BUS' failed: $?"
 		else
-			log "rm -f 'bus/usb/$BUS/$USB_DEV' failed"
-			exit 0
+			log "rm -f 'bus/usb/$BUS/$USB_DEV' failed: $?"
+			exit 1
 		fi
 		;;
 esac
