sys-apps/busybox-1.20.2 update

diff --git a/sys-apps/busybox/files/mdev/usb b/sys-apps/busybox/files/mdev/usb
--- a/sys-apps/busybox/files/mdev/usb
+++ b/sys-apps/busybox/files/mdev/usb
@@ -12,7 +12,7 @@ echo >>"$LOGFILE" "$$ $( date +"%T.%N" ) mdev usb helper started as '$0' in '$( 
 [ -n "$DEVPATH" ] || exit 0
 [ "$SUBSYSTEM" = "usb" ] || exit 0
 
-# add zeros to device or bus
+# Add zeros to device or bus identifiers
 function add_zeros() {
 	case "$( echo "$1" | wc -L )" in
 		1)	echo "00$1"
@@ -26,8 +26,10 @@ function add_zeros() {
 }
 
 # e.g. DEVPATH=/devices/pci0000:00/0000:00:0f.4/usb2/2-1, MDEV=2-1
+#  or  DEVPATH=/devices/platform/bcm2708_usb/usb1/1-1/1-1.1, MDEV=1-1.1
 BUS=""
 USB_DEV=""
+#USB_FUNC="$( add_zeros "$( echo "$MDEV" | cut -d'-' -f 2 )" )"
 if [ -d /sys/devices ]; then
 	BUS="$( add_zeros "$( cat "/sys$DEVPATH/busnum" 2>/dev/null )" )"
 	USB_DEV="$( add_zeros "$( cat "/sys$DEVPATH/devnum" 2>/dev/null )" )"
@@ -36,16 +38,23 @@ if [ -z "$BUS" ]; then
 	BUS="$( add_zeros "$( echo "$DEVPATH" | cut -d'/' -f 5 | sed 's/^usb//' )" )"
 fi
 if [ -z "$USB_DEV" ]; then
-	USB_DEV="$( add_zeros "$( echo "$MDEV" | cut -d'-' -f 1 )" )"
+	# Some guesswork is involved here...
+	USB_DEV="$( echo "$MDEV" | cut -d'-' -f 1 )"
+	USB_DEV="$( expr $USB_DEV + $( echo "$MDEV" | cut -d'-' -f 2 | cut -d'.' -f 1 ) )"
+	USB_DEV="$( expr $USB_DEV + $( echo "$MDEV" | cut -d'.' -f 2 ) )"
+	USB_DEV="$( add_zeros "$USB_DEV" )"
 fi
-#USB_FUNC="$( add_zeros "$( echo "$MDEV" | cut -d'-' -f 2 )" )"
 
-# try to load the proper driver for usb devices
+if ! [ -n "$BUS" && -n "$USB_DEV" ]; then
+	echo >>"LOGFILE" "$$ $( date +"%T.%N" ) Could not determine BUS and DEVICE information for node '$MDEV' - aborting"
+	exit 1
+fi
+
 case "$ACTION" in
 	add|"")
 		echo >>"$LOGFILE" "$$ $( date +"%T.%N" ) Performing 'add' ACTION"
 
-		# move usb device file
+		# Move USB device node
 		if [ ! -d "bus/usb/$BUS" ]; then
 			echo >>"$LOGFILE" "$$ $( date +"%T.%N" ) WARNING USB bus directory 'bus/usb/$BUS' doesn't exist - is USB initialised?"
 			mkdir -p "bus/usb/$BUS" \
@@ -59,7 +68,7 @@ case "$ACTION" in
 	remove)
 		echo >>"$LOGFILE" "$$ $( date +"%T.%N" ) Performing 'add' ACTION"
 
-		# remove device file and possible empty dirs
+		# Remove device node and potential empty directories
 		if rm -f "bus/usb/$BUS/$USB_DEV" 2>/dev/null \
 			&& echo >>"$LOGFILE" "$$ $( date +"%T.%N" ) rm -f 'bus/usb/$BUS/$USB_DEV' succeeded"
 		then
